[package]
authors = ["Nick Fitzgerald <fitzgen@gmail.com>"]
name = "clife"
version = "0.1.0"

[dependencies]
crossbeam = "0.1.6"
docopt = "0.6.75"
glium = "0.11.1"
rand = "0.3.12"
rustc-serialize = "0.3.16"
threadpool = "0.1.4"
